name: Create release upon tag creation

on: # Only run on new version tag push
  push:
    tags: [ v* ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: write
  
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          draft: true
          generate_release_notes: true
